# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-12 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(default='vazio')),
                ('campo2', models.TextField(default='vazio')),
                ('campo3', models.TextField(default='vazio')),
                ('campo4', models.TextField(default='vazio')),
                ('campo5', models.TextField(default='vazio')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('campo1', models.CharField(max_length=50)),
                ('campo2', models.CharField(max_length=50)),
                ('campo3', models.CharField(max_length=50)),
                ('campo4', models.CharField(max_length=50)),
                ('campo5', models.CharField(max_length=50)),
            ],
        ),
    ]
