# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-16 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('metodo', models.TextField()),
                ('consulta', models.BooleanField(default=False)),
                ('consulta_url', models.TextField(default=None)),
                ('consulta_metodo', models.TextField(default=None)),
                ('consulta_step2', models.TextField(default=None)),
                ('campo1', models.TextField(default=None)),
                ('campo2', models.TextField(default=None)),
                ('campo3', models.TextField(default=None)),
                ('campo4', models.TextField(default=None)),
                ('campo5', models.TextField(default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
