# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_spider', '0002_auto_20180812_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='campo1',
            field=models.TextField(default='vazio'),
        ),
    ]
