# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_spider', '0003_extract_campo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='fonte',
            field=models.TextField(default='vazio'),
        ),
    ]
