# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_spider', '0004_extract_fonte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spider',
            name='author',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='spider',
            name='campo1',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='spider',
            name='campo2',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='spider',
            name='campo3',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='spider',
            name='campo4',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='spider',
            name='campo5',
            field=models.CharField(default='', max_length=150),
        ),
    ]
